// resources/js/components/entries/KeyValueEntry.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Button } from '@/components/ui/button'
import { Copy } from 'lucide-vue-next'
import { useNotification } from '@laravilt/notifications/composables/useNotification'
import { formatStateValue } from '../../lib/entries'

const { notify } = useNotification()

interface KeyValueEntryProps {
  label: string
  state: any
  placeholder?: string
  keyLabel?: string
  valueLabel?: string
  copyableKeys?: boolean
  copyableValues?: boolean
}

const props = withDefaults(defineProps<KeyValueEntryProps>(), {
  placeholder: '—',
  keyLabel: 'Key',
  valueLabel: 'Value',
  copyableKeys: false,
  copyableValues: false,
})

const entries = computed(() => {
  if (!props.state || typeof props.state !== 'object') {
    return []
  }

  return Object.entries(props.state).map(([key, value]) => ({
    key,
    // Nested objects / arrays as JSON / joined text instead of "[object Object]"
    value: formatStateValue(value),
  }))
})

const handleCopyKey = (key: string) => {
  navigator.clipboard.writeText(key)
  notify({
    title: 'Copied',
    body: 'Key copied to clipboard',
    type: 'success',
  })
}

const handleCopyValue = (value: string) => {
  navigator.clipboard.writeText(value)
  notify({
    title: 'Copied',
    body: 'Value copied to clipboard',
    type: 'success',
  })
}
</script>

<template>
  <div class="flex flex-col gap-1">
    <div class="text-sm font-medium text-foreground">
      {{ label }}
    </div>
    <div v-if="entries.length > 0" class="rounded-md border border-border overflow-hidden">
      <table class="w-full text-sm">
        <thead class="bg-muted/50">
          <tr>
            <th class="px-4 py-2 text-left font-medium text-foreground">
              {{ keyLabel }}
            </th>
            <th class="px-4 py-2 text-left font-medium text-foreground">
              {{ valueLabel }}
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-border">
          <tr
            v-for="(entry, index) in entries"
            :key="index"
            class="hover:bg-muted/30"
          >
            <td class="px-4 py-2">
              <div class="flex items-center gap-2">
                <span class="font-medium text-foreground">{{ entry.key }}</span>
                <Button
                  v-if="copyableKeys"
                  variant="ghost"
                  size="icon"
                  class="h-6 w-6 shrink-0"
                  @click="handleCopyKey(entry.key)"
                >
                  <Copy class="h-3 w-3" />
                </Button>
              </div>
            </td>
            <td class="px-4 py-2">
              <div class="flex items-center gap-2">
                <span class="text-muted-foreground">{{ entry.value }}</span>
                <Button
                  v-if="copyableValues"
                  variant="ghost"
                  size="icon"
                  class="h-6 w-6 shrink-0"
                  @click="handleCopyValue(entry.value)"
                >
                  <Copy class="h-3 w-3" />
                </Button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <span v-else class="text-sm text-muted-foreground italic">
      {{ placeholder }}
    </span>
  </div>
</template>

// resources/react/components/entries/KeyValueEntry.tsx
import { Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { useNotification } from '@laravilt/notifications/composables/useNotification';
import { formatStateValue } from '../../lib/entries';

export interface KeyValueEntryProps {
    label: string;
    state: any;
    placeholder?: string;
    keyLabel?: string;
    valueLabel?: string;
    copyableKeys?: boolean;
    copyableValues?: boolean;
    /** Vue fall-through `class`. */
    className?: string;
}

export default function KeyValueEntry({
    label,
    state,
    placeholder = '—',
    keyLabel = 'Key',
    valueLabel = 'Value',
    copyableKeys = false,
    copyableValues = false,
    className,
}: KeyValueEntryProps) {
    const { notify } = useNotification();

    const entries: { key: string; value: string }[] =
        !state || typeof state !== 'object'
            ? []
            : Object.entries(state).map(([key, value]) => ({
                  key,
                  // Nested objects / arrays as JSON / joined text instead of "[object Object]"
                  value: formatStateValue(value),
              }));

    const handleCopyKey = (key: string) => {
        navigator.clipboard.writeText(key);
        notify({
            title: 'Copied',
            body: 'Key copied to clipboard',
            type: 'success',
        });
    };

    const handleCopyValue = (value: string) => {
        navigator.clipboard.writeText(value);
        notify({
            title: 'Copied',
            body: 'Value copied to clipboard',
            type: 'success',
        });
    };

    return (
        <div className={cn('flex flex-col gap-1', className)}>
            <div className="text-sm font-medium text-foreground">{label}</div>
            {entries.length > 0 ? (
                <div className="rounded-md border border-border overflow-hidden">
                    <table className="w-full text-sm">
                        <thead className="bg-muted/50">
                            <tr>
                                <th className="px-4 py-2 text-left font-medium text-foreground">{keyLabel}</th>
                                <th className="px-4 py-2 text-left font-medium text-foreground">{valueLabel}</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-border">
                            {entries.map((entry, index) => (
                                <tr key={index} className="hover:bg-muted/30">
                                    <td className="px-4 py-2">
                                        <div className="flex items-center gap-2">
                                            <span className="font-medium text-foreground">{entry.key}</span>
                                            {copyableKeys && (
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    className="h-6 w-6 shrink-0"
                                                    onClick={() => handleCopyKey(entry.key)}
                                                >
                                                    <Copy className="h-3 w-3" />
                                                </Button>
                                            )}
                                        </div>
                                    </td>
                                    <td className="px-4 py-2">
                                        <div className="flex items-center gap-2">
                                            <span className="text-muted-foreground">{entry.value}</span>
                                            {copyableValues && (
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    className="h-6 w-6 shrink-0"
                                                    onClick={() => handleCopyValue(entry.value)}
                                                >
                                                    <Copy className="h-3 w-3" />
                                                </Button>
                                            )}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            ) : (
                <span className="text-sm text-muted-foreground italic">{placeholder}</span>
            )}
        </div>
    );
}

export { KeyValueEntry };
