// resources/react/components/InfoList.tsx
import { Fragment, type ComponentType } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { resolveIcon } from '@laravilt/support/lib/icons';
import BadgeEntry from './entries/BadgeEntry';
import CodeEntry from './entries/CodeEntry';
import ColorEntry from './entries/ColorEntry';
import IconEntry from './entries/IconEntry';
import ImageEntry from './entries/ImageEntry';
import KeyValueEntry from './entries/KeyValueEntry';
import RepeatableEntry from './entries/RepeatableEntry';
import TextEntry from './entries/TextEntry';

export interface InfoListEntry {
    component: string;
    name: string;
    label: string;
    value?: any;
    state?: any;
    schema?: InfoListEntry[];
    description?: string;
    columns?: number;
    columnSpan?: number | string | Record<string, number | string>;
    tabs?: InfoListEntry[];
    [key: string]: any;
}

export interface InfoListProps {
    schema: InfoListEntry[];
}

const componentMap: Record<string, ComponentType<any>> = {
    TextEntry,
    IconEntry,
    ImageEntry,
    ColorEntry,
    CodeEntry,
    KeyValueEntry,
    RepeatableEntry,
    BadgeEntry,
    // The server sends snake_case types (Laravilt\Support\Component::getComponentType)
    text_entry: TextEntry,
    icon_entry: IconEntry,
    image_entry: ImageEntry,
    color_entry: ColorEntry,
    code_entry: CodeEntry,
    key_value_entry: KeyValueEntry,
    repeatable_entry: RepeatableEntry,
    badge_entry: BadgeEntry,
};

const getEntryComponent = (componentType: string): ComponentType<any> => {
    return componentMap[componentType] || TextEntry;
};

const LAYOUT_TYPES = ['section', 'grid', 'tabs'];

// Helper to check component type (case insensitive)
const isComponent = (item: InfoListEntry, type: string) => {
    return (item.component || '').toLowerCase() === type.toLowerCase();
};

const getGridClass = (columns?: number): string => {
    if (!columns || columns === 1) return 'md:grid-cols-1';
    if (columns === 2) return 'md:grid-cols-2';
    if (columns === 3) return 'md:grid-cols-3';
    if (columns === 4) return 'md:grid-cols-4';
    if (columns === 5) return 'md:grid-cols-5';
    if (columns === 6) return 'md:grid-cols-6';

    return 'md:grid-cols-1';
};

const getColumnSpanClass = (columnSpan?: number | string | Record<string, number | string>): string => {
    if (!columnSpan) return '';

    // Handle 'full' string
    if (columnSpan === 'full') return 'col-span-full';

    // Handle integer
    if (typeof columnSpan === 'number') {
        return `md:col-span-${columnSpan}`;
    }

    // Handle responsive object: { md: 2, xl: 4 }
    if (typeof columnSpan === 'object') {
        const classes: string[] = [];

        // Handle default key (for sm and below)
        if ('default' in columnSpan) {
            const defaultSpan = columnSpan.default;

            if (defaultSpan === 'full') {
                classes.push('col-span-full');
            } else {
                classes.push(`col-span-${defaultSpan}`);
            }
        }

        // Handle responsive breakpoints
        for (const [breakpoint, span] of Object.entries(columnSpan)) {
            if (breakpoint === 'default') continue;

            if (span === 'full') {
                classes.push(`${breakpoint}:col-span-full`);
            } else {
                classes.push(`${breakpoint}:col-span-${span}`);
            }
        }

        return classes.join(' ');
    }

    return '';
};

/** `<component :is="getEntryComponent(entry.component)" :class="…" v-bind="{ ...entry, state: entry.value ?? entry.state }" />` */
function renderEntry(entry: InfoListEntry, key: string | number) {
    const Entry = getEntryComponent(entry.component);

    return <Entry key={key} {...entry} state={entry.value ?? entry.state} className={getColumnSpanClass(entry.columnSpan)} />;
}

function SectionHeader({ item }: { item: InfoListEntry }) {
    if (!(item.label || item.heading)) {
        return null;
    }

    const Icon = item.icon ? resolveIcon(item.icon) : null;

    return (
        <header className="px-6 py-4 border-b">
            <div className="flex items-center gap-3">
                {item.icon && Icon && (
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0">
                        <Icon className="h-5 w-5" />
                    </div>
                )}
                <div className="flex-1 min-w-0">
                    <h3 className="leading-none font-semibold">{item.label || item.heading}</h3>
                    {item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}
                </div>
            </div>
        </header>
    );
}

export default function InfoList({ schema }: InfoListProps) {
    // Separate layout components from entries
    const layoutComponents =
        !schema || !Array.isArray(schema)
            ? []
            : schema.filter((item) => LAYOUT_TYPES.includes((item.component || '').toLowerCase()));

    const entries =
        !schema || !Array.isArray(schema)
            ? []
            : schema.filter((item) => !LAYOUT_TYPES.includes((item.component || '').toLowerCase()));

    return (
        <div className="space-y-6">
            {/* Render layout components (Section, Grid, Tabs) */}
            {layoutComponents.map((layout) => (
                <Fragment key={layout.label || layout.name}>
                    {isComponent(layout, 'section') ? (
                        /* Section Component */
                        <div className="bg-card text-card-foreground rounded-xl border shadow-sm">
                            <SectionHeader item={layout} />
                            <div className="p-6">
                                <div className="space-y-6">
                                    {(layout.schema ?? []).map((item) => (
                                        <Fragment key={item.name}>
                                            {isComponent(item, 'grid') ? (
                                                /* Nested Grid within Section */
                                                <div className={`grid gap-6 ${getGridClass(item.columns)}`}>
                                                    {(item.schema ?? []).map((entry) => renderEntry(entry, entry.name))}
                                                </div>
                                            ) : (
                                                /* Direct Entry within Section */
                                                renderEntry(item, item.name)
                                            )}
                                        </Fragment>
                                    ))}
                                </div>
                            </div>
                        </div>
                    ) : isComponent(layout, 'grid') ? (
                        /* Grid Component */
                        <div className={`grid gap-6 ${getGridClass(layout.columns)}`}>
                            {(layout.schema ?? []).map((entry) => renderEntry(entry, entry.name))}
                        </div>
                    ) : isComponent(layout, 'tabs') ? (
                        /* Tabs Component */
                        <Tabs defaultValue={layout.tabs?.[0]?.label || 'tab-0'}>
                            <TabsList>
                                {(layout.tabs ?? []).map((tab, index) => (
                                    <TabsTrigger key={tab.label || `tab-${index}`} value={tab.label || `tab-${index}`}>
                                        {tab.label}
                                    </TabsTrigger>
                                ))}
                            </TabsList>
                            {(layout.tabs ?? []).map((tab, index) => (
                                <TabsContent key={tab.label || `tab-${index}`} value={tab.label || `tab-${index}`} className="mt-6">
                                    <div className="space-y-6">
                                        {/* Recursively render layout components within tabs */}
                                        {(tab.schema ?? []).map((item) => (
                                            <Fragment key={item.name}>
                                                {isComponent(item, 'section') ? (
                                                    /* Section within Tab */
                                                    <div className="bg-card text-card-foreground rounded-xl border shadow-sm">
                                                        <SectionHeader item={item} />
                                                        <div className="p-6">
                                                            <div className={`grid gap-6 ${getGridClass(item.columns)}`}>
                                                                {(item.schema ?? []).map((entry) => renderEntry(entry, entry.name))}
                                                            </div>
                                                        </div>
                                                    </div>
                                                ) : isComponent(item, 'grid') ? (
                                                    /* Grid within Tab */
                                                    <div className={`grid gap-6 ${getGridClass(item.columns)}`}>
                                                        {(item.schema ?? []).map((entry) => renderEntry(entry, entry.name))}
                                                    </div>
                                                ) : (
                                                    /* Regular entries within Tab */
                                                    renderEntry(item, item.name)
                                                )}
                                            </Fragment>
                                        ))}
                                    </div>
                                </TabsContent>
                            ))}
                        </Tabs>
                    ) : null}
                </Fragment>
            ))}

            {/* If there are no layout components, render entries directly without card wrapper */}
            {layoutComponents.length === 0 && entries.length > 0 && (
                <div className="grid gap-6">{entries.map((entry) => renderEntry(entry, entry.name))}</div>
            )}
        </div>
    );
}

export { InfoList };

// resources/js/components/InfoList.vue
<script setup lang="ts">
import { computed } from 'vue'
import TextEntry from './entries/TextEntry.vue'
import IconEntry from './entries/IconEntry.vue'
import ImageEntry from './entries/ImageEntry.vue'
import ColorEntry from './entries/ColorEntry.vue'
import CodeEntry from './entries/CodeEntry.vue'
import KeyValueEntry from './entries/KeyValueEntry.vue'
import RepeatableEntry from './entries/RepeatableEntry.vue'
import BadgeEntry from './entries/BadgeEntry.vue'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import * as LucideIcons from 'lucide-vue-next'

interface InfoListEntry {
  component: string
  name: string
  label: string
  value?: any
  state?: any
  schema?: InfoListEntry[]
  description?: string
  columns?: number
  columnSpan?: number | string | Record<string, number | string>
  tabs?: InfoListEntry[]
  [key: string]: any
}

interface InfoListProps {
  schema: InfoListEntry[]
}

const props = defineProps<InfoListProps>()

const getEntryComponent = (componentType: string) => {
  const componentMap: Record<string, any> = {
    TextEntry,
    IconEntry,
    ImageEntry,
    ColorEntry,
    CodeEntry,
    KeyValueEntry,
    RepeatableEntry,
    BadgeEntry,
    // The server sends snake_case types (Laravilt\Support\Component::getComponentType)
    text_entry: TextEntry,
    icon_entry: IconEntry,
    image_entry: ImageEntry,
    color_entry: ColorEntry,
    code_entry: CodeEntry,
    key_value_entry: KeyValueEntry,
    repeatable_entry: RepeatableEntry,
    badge_entry: BadgeEntry,
  }

  return componentMap[componentType] || TextEntry
}

// Separate layout components from entries
const layoutComponents = computed(() => {
  if (!props.schema || !Array.isArray(props.schema)) return []
  return props.schema.filter(item => {
    const componentType = (item.component || '').toLowerCase()
    return ['section', 'grid', 'tabs'].includes(componentType)
  })
})

const entries = computed(() => {
  if (!props.schema || !Array.isArray(props.schema)) return []
  return props.schema.filter(item => {
    const componentType = (item.component || '').toLowerCase()
    return !['section', 'grid', 'tabs'].includes(componentType)
  })
})

// Helper to check component type (case insensitive)
const isComponent = (item: InfoListEntry, type: string) => {
  return (item.component || '').toLowerCase() === type.toLowerCase()
}

const getGridClass = (columns?: number) => {
  if (!columns || columns === 1) return 'md:grid-cols-1'
  if (columns === 2) return 'md:grid-cols-2'
  if (columns === 3) return 'md:grid-cols-3'
  if (columns === 4) return 'md:grid-cols-4'
  if (columns === 5) return 'md:grid-cols-5'
  if (columns === 6) return 'md:grid-cols-6'
  return 'md:grid-cols-1'
}

const getColumnSpanClass = (columnSpan?: number | string | Record<string, number | string>) => {
  if (!columnSpan) return ''

  // Handle 'full' string
  if (columnSpan === 'full') return 'col-span-full'

  // Handle integer
  if (typeof columnSpan === 'number') {
    return `md:col-span-${columnSpan}`
  }

  // Handle responsive object: { md: 2, xl: 4 }
  if (typeof columnSpan === 'object') {
    const classes: string[] = []

    // Handle default key (for sm and below)
    if ('default' in columnSpan) {
      const defaultSpan = columnSpan.default
      if (defaultSpan === 'full') {
        classes.push('col-span-full')
      } else {
        classes.push(`col-span-${defaultSpan}`)
      }
    }

    // Handle responsive breakpoints
    for (const [breakpoint, span] of Object.entries(columnSpan)) {
      if (breakpoint === 'default') continue

      if (span === 'full') {
        classes.push(`${breakpoint}:col-span-full`)
      } else {
        classes.push(`${breakpoint}:col-span-${span}`)
      }
    }

    return classes.join(' ')
  }

  return ''
}

// Convert kebab-case or snake_case icon names to PascalCase for lucide-vue-next
const getIconComponent = (iconName: string) => {
  if (!iconName) return null

  // Convert formats like 'user', 'id-card', 'map-pin' to PascalCase
  const pascalCase = iconName
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')

  return (LucideIcons as any)[pascalCase] || null
}
</script>

<template>
  <div class="space-y-6">
    <!-- Render layout components (Section, Grid, Tabs) -->
    <template v-for="layout in layoutComponents" :key="layout.label || layout.name">
      <!-- Section Component -->
      <div v-if="isComponent(layout, 'section')" class="bg-card text-card-foreground rounded-xl border shadow-sm">
        <header v-if="layout.label || layout.heading" class="px-6 py-4 border-b">
          <div class="flex items-center gap-3">
            <div
              v-if="layout.icon && getIconComponent(layout.icon)"
              class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0"
            >
              <component
                :is="getIconComponent(layout.icon)"
                class="h-5 w-5"
              />
            </div>
            <div class="flex-1 min-w-0">
              <h3 class="leading-none font-semibold">{{ layout.label || layout.heading }}</h3>
              <p v-if="layout.description" class="mt-1 text-sm text-muted-foreground">
                {{ layout.description }}
              </p>
            </div>
          </div>
        </header>
        <div class="p-6">
          <div class="space-y-6">
            <template v-for="item in layout.schema" :key="item.name">
              <!-- Nested Grid within Section -->
              <div v-if="isComponent(item, 'grid')" class="grid gap-6" :class="getGridClass(item.columns)">
                <component
                  v-for="entry in item.schema"
                  :key="entry.name"
                  :is="getEntryComponent(entry.component)"
                  :class="getColumnSpanClass(entry.columnSpan)"
                  v-bind="{ ...entry, state: entry.value ?? entry.state }"
                />
              </div>
              <!-- Direct Entry within Section -->
              <component
                v-else
                :is="getEntryComponent(item.component)"
                :class="getColumnSpanClass(item.columnSpan)"
                v-bind="{ ...item, state: item.value ?? item.state }"
              />
            </template>
          </div>
        </div>
      </div>

      <!-- Grid Component -->
      <div v-else-if="isComponent(layout, 'grid')" class="grid gap-6" :class="getGridClass(layout.columns)">
        <component
          v-for="entry in layout.schema"
          :key="entry.name"
          :is="getEntryComponent(entry.component)"
          :class="getColumnSpanClass(entry.columnSpan)"
          v-bind="{ ...entry, state: entry.value ?? entry.state }"
        />
      </div>

      <!-- Tabs Component -->
      <Tabs v-else-if="isComponent(layout, 'tabs')" :default-value="layout.tabs?.[0]?.label || 'tab-0'">
        <TabsList>
          <TabsTrigger
            v-for="(tab, index) in layout.tabs"
            :key="tab.label || `tab-${index}`"
            :value="tab.label || `tab-${index}`"
          >
            {{ tab.label }}
          </TabsTrigger>
        </TabsList>
        <TabsContent
          v-for="(tab, index) in layout.tabs"
          :key="tab.label || `tab-${index}`"
          :value="tab.label || `tab-${index}`"
          class="mt-6"
        >
          <div class="space-y-6">
            <!-- Recursively render layout components within tabs -->
            <template v-for="item in tab.schema" :key="item.name">
              <!-- Section within Tab -->
              <div v-if="isComponent(item, 'section')" class="bg-card text-card-foreground rounded-xl border shadow-sm">
                <header v-if="item.label || item.heading" class="px-6 py-4 border-b">
                  <div class="flex items-center gap-3">
                    <div
                      v-if="item.icon && getIconComponent(item.icon)"
                      class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary flex-shrink-0"
                    >
                      <component
                        :is="getIconComponent(item.icon)"
                        class="h-5 w-5"
                      />
                    </div>
                    <div class="flex-1 min-w-0">
                      <h3 class="leading-none font-semibold">{{ item.label || item.heading }}</h3>
                      <p v-if="item.description" class="mt-1 text-sm text-muted-foreground">
                        {{ item.description }}
                      </p>
                    </div>
                  </div>
                </header>
                <div class="p-6">
                  <div class="grid gap-6" :class="getGridClass(item.columns)">
                    <component
                      v-for="entry in item.schema"
                      :key="entry.name"
                      :is="getEntryComponent(entry.component)"
                      :class="getColumnSpanClass(entry.columnSpan)"
                      v-bind="{ ...entry, state: entry.value ?? entry.state }"
                    />
                  </div>
                </div>
              </div>

              <!-- Grid within Tab -->
              <div v-else-if="isComponent(item, 'grid')" class="grid gap-6" :class="getGridClass(item.columns)">
                <component
                  v-for="entry in item.schema"
                  :key="entry.name"
                  :is="getEntryComponent(entry.component)"
                  :class="getColumnSpanClass(entry.columnSpan)"
                  v-bind="{ ...entry, state: entry.value ?? entry.state }"
                />
              </div>

              <!-- Regular entries within Tab -->
              <component
                v-else
                :is="getEntryComponent(item.component)"
                :class="getColumnSpanClass(item.columnSpan)"
                v-bind="{ ...item, state: item.value ?? item.state }"
              />
            </template>
          </div>
        </TabsContent>
      </Tabs>
    </template>

    <!-- If there are no layout components, render entries directly without card wrapper -->
    <div v-if="layoutComponents.length === 0 && entries.length > 0" class="grid gap-6">
      <component
        v-for="entry in entries"
        :key="entry.name"
        :is="getEntryComponent(entry.component)"
        :class="getColumnSpanClass(entry.columnSpan)"
        v-bind="{ ...entry, state: entry.value ?? entry.state }"
      />
    </div>
  </div>
</template>
