// resources/react/components/entries/CodeEntry.tsx
import { Copy } from 'lucide-react';
import type { CSSProperties } from 'react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { useNotification } from '@laravilt/notifications/composables/useNotification';
import { isEmptyState } from '../../lib/entries';

export interface CodeEntryProps {
    label: string;
    state: any;
    placeholder?: string;
    copyable?: boolean;
    language?: string;
    maxHeight?: number | null;
    lineNumbers?: boolean;
    /** Vue fall-through `class`. */
    className?: string;
}

export default function CodeEntry({
    label,
    state,
    placeholder = '—',
    copyable = true,
    maxHeight = null,
    lineNumbers = true,
    className,
}: CodeEntryProps) {
    const { notify } = useNotification();

    const codeStyle: CSSProperties = {};

    if (maxHeight) {
        codeStyle.maxHeight = `${maxHeight}px`;
        codeStyle.overflow = 'auto';
    }

    // Objects / arrays are shown as indented JSON; 0 and false are real values
    const codeText = (() => {
        if (isEmptyState(state)) return '';
        if (typeof state === 'object') {
            try {
                return JSON.stringify(state, null, 2);
            } catch {
                return String(state);
            }
        }
        return String(state);
    })();

    const codeLines: string[] = isEmptyState(state) ? [] : codeText.split('\n');

    const handleCopy = () => {
        if (copyable && !isEmptyState(state)) {
            navigator.clipboard.writeText(codeText);
            notify({
                title: 'Copied',
                body: 'Code copied to clipboard',
                type: 'success',
            });
        }
    };

    return (
        <div className={cn('flex flex-col gap-1', className)}>
            <div className="flex items-center justify-between">
                <div className="text-sm font-medium text-foreground">{label}</div>
                {copyable && !isEmptyState(state) && (
                    <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={handleCopy}>
                        <Copy className="h-3 w-3" />
                    </Button>
                )}
            </div>
            {!isEmptyState(state) ? (
                <div className="rounded-md border border-border bg-muted/30 overflow-hidden" style={codeStyle}>
                    <pre className="p-4 text-sm overflow-x-auto">
                        <code className="font-mono">
                            {lineNumbers
                                ? codeLines.map((line, index) => (
                                      <span key={index} className="block">
                                          <span className="inline-block w-8 text-muted-foreground select-none text-right mr-4">
                                              {index + 1}
                                          </span>
                                          <span>{line}</span>
                                      </span>
                                  ))
                                : codeText}
                        </code>
                    </pre>
                </div>
            ) : (
                <span className="text-sm text-muted-foreground italic">{placeholder}</span>
            )}
        </div>
    );
}

export { CodeEntry };

// resources/js/components/entries/CodeEntry.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Button } from '@/components/ui/button'
import { Copy } from 'lucide-vue-next'
import { useNotification } from '@laravilt/notifications/composables/useNotification'
import { isEmptyState } from '../../lib/entries'

const { notify } = useNotification()

interface CodeEntryProps {
  label: string
  state: any
  placeholder?: string
  copyable?: boolean
  language?: string
  maxHeight?: number | null
  lineNumbers?: boolean
}

const props = withDefaults(defineProps<CodeEntryProps>(), {
  placeholder: '—',
  copyable: true,
  language: 'plaintext',
  maxHeight: null,
  lineNumbers: true,
})

const codeStyle = computed(() => {
  const style: Record<string, string> = {}

  if (props.maxHeight) {
    style.maxHeight = `${props.maxHeight}px`
    style.overflow = 'auto'
  }

  return style
})

// Objects / arrays are shown as indented JSON; 0 and false are real values
const codeText = computed(() => {
  if (isEmptyState(props.state)) return ''
  if (typeof props.state === 'object') {
    try {
      return JSON.stringify(props.state, null, 2)
    } catch {
      return String(props.state)
    }
  }
  return String(props.state)
})

const codeLines = computed(() => {
  if (isEmptyState(props.state)) return []
  return codeText.value.split('\n')
})

const handleCopy = () => {
  if (props.copyable && !isEmptyState(props.state)) {
    navigator.clipboard.writeText(codeText.value)
    notify({
      title: 'Copied',
      body: 'Code copied to clipboard',
      type: 'success',
    })
  }
}
</script>

<template>
  <div class="flex flex-col gap-1">
    <div class="flex items-center justify-between">
      <div class="text-sm font-medium text-foreground">
        {{ label }}
      </div>
      <Button
        v-if="copyable && !isEmptyState(state)"
        variant="ghost"
        size="icon"
        class="h-6 w-6 shrink-0"
        @click="handleCopy"
      >
        <Copy class="h-3 w-3" />
      </Button>
    </div>
    <div
      v-if="!isEmptyState(state)"
      class="rounded-md border border-border bg-muted/30 overflow-hidden"
      :style="codeStyle"
    >
      <pre class="p-4 text-sm overflow-x-auto"><code class="font-mono"><template v-if="lineNumbers"><span
            v-for="(line, index) in codeLines"
            :key="index"
            class="block"
          ><span class="inline-block w-8 text-muted-foreground select-none text-right mr-4">{{ index + 1 }}</span><span>{{ line }}</span></span></template><template v-else>{{ codeText }}</template></code></pre>
    </div>
    <span v-else class="text-sm text-muted-foreground italic">
      {{ placeholder }}
    </span>
  </div>
</template>
